### ISSUE TITLE
typora 打开不对

### ISSUE THREAD

**Issue by newyorkthink** [BingyanStudio/LapisCV#1]
![image](https://github.com/BingyanStudio/LapisCV/assets/87791643/ca81a40e-1be5-49e2-b490-d202a4fc4208)
![image](https://github.com/BingyanStudio/LapisCV/assets/87791643/4f89d3a3-4b8a-4181-95dd-b5a3cb458cfd)

**Comment by YiNNx** [comment]
看起来主题没有正确加载出来，可以试试重启Typora然后再切换Lapis Cv主题试试

**Comment by zd200572** [comment]
是不是有软件版本兼容性问题，我也是重启找不到这个主题

**Comment by YiNNx** [comment]
> 是不是有软件版本兼容性问题，我也是重启找不到这个主题

可能是因为把整个目录都放进主题文件夹了，Typora 加载主题需要确保 lapis-cv.css 放在主题文件夹根目录

**Comment by YiNNx** [comment]
重新在 README 里更新了详细的安装步骤，可能是之前的安装说明不够明确
