### ISSUE TITLE
如何放一张完整的图片呢？

### ISSUE THREAD

**Issue by 1kepingguo** [BingyanStudio/LapisCV#12]
请教大佬，使用头像时由于图像的纵横比问题，总是显示不全，感觉很别扭，请问有什么解决办法吗？感谢！！

**Comment by universeXiong** [comment]
提前吧图片裁剪好再放到markdown里面

**Comment by 1kepingguo** [comment]
好的谢谢大佬，我这边采用了更改头像的宽高比来适应图片，并取消圆角边框，这样可以显示正常图片。
