### ISSUE TITLE
如何调整生成pdf后，头像的位置

### ISSUE THREAD

**Issue by 1kepingguo** [BingyanStudio/LapisCV#13]
![25f9a52fdc9655ce6daa8910e0acb3a](https://github.com/user-attachments/assets/682db7a6-d211-4097-96d3-a4a32e69a09e)
打扰大佬，头像的位置有些偏下，请问可以往上调整些嘛？

**Comment by YiNNx** [comment]
可以自行修改css来调整样式，具体控制头像高度位置的字段如图下

![image](https://github.com/user-attachments/assets/6056c7dc-530f-4f3e-ada0-e10425114f4f)

**Comment by Yinlin124** [comment]
实测调整 print 中的参数有效

> 可以自行修改css来调整样式，具体控制头像高度位置的字段如图下
> 
> ![image](https://private-user-images.githubusercontent.com/86649490/349448165-6056c7dc-530f-4f3e-ada0-e10425114f4f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTU1MDYsIm5iZiI6MTcyMTU1NTIwNiwicGF0aCI6Ii84NjY0OTQ5MC8zNDk0NDgxNjUtNjA1NmM3ZGMtNTMwZi00ZjNlLWFkYTAtZTEwNDI1MTE0ZjRmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwOTQ2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjUxZmE2ZWRkNWYwMjc5NjJjZjQ5Y2ZkMzQ5ZDA0ZTE1MGI1M2IwZWMxOGFjYzMzZWQ5NmEzNDk0MjJhOWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c6SiRCxMaAOlfXAd-E-W-kdPQEgihJBv3QKHHnvu1xI)

**Comment by 1kepingguo** [comment]
print是调整pdf的上下左右的页边距吧，图像在整体页面中的位置还是要靠css调，不过可调整余地不多



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yinlin124 ***@***.***&gt;
发送时间: 2024年7月21日 17:57
收件人: BingyanStudio/LapisCV ***@***.***&gt;
抄送: 1kepingguo ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [BingyanStudio/LapisCV] 如何调整生成pdf后，头像的位置 (Issue #13)

**Comment by KelinGoon** [comment]
> print是调整pdf的上下左右的页边距吧，图像在整体页面中的位置还是要靠css调整，不过可调整余地不太发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yinlin124 ***@*** .***> 发送时间：2024年7月21日 17:57 食谱：BingyanStudio/LapisCV ***@***.***> 抄送：1kepingguo ***@***.***>，作者***@***.***> 主题: Re: [BingyanStudio/LapisCV] 如何调整生成pdf后，头像的位置 (Issue #13 )

解决了吗

**Comment by 1kepingguo** [comment]
感谢感谢，亲测有效。谢谢大佬们。

**Comment by meilijunxi** [comment]
为什么我调整了没用？怎么调整才能让图像和姓名对齐啊？ @YiNNx
