### ISSUE TITLE
Layout and Spacing Challenges in Translating a Chinese Resume Template to English

### ISSUE THREAD

**Issue by syhxzzz** [BingyanStudio/LapisCV#22]
When using this project to create an English resume, I encountered several layout and formatting issues. The original resume template was designed for Chinese, and directly translating the content into English increases the resume length from one page to about one and a half pages.

<img width="720" alt="image" src="https://github.com/user-attachments/assets/319acc5f-299a-47b1-8cb9-38390e401e4c">

To maintain a one-page resume, it’s necessary to **reorganize English content** and **optimize layout**. Here are a few specific **suggestions for optimizing layout**:

1. Adjust Line Spacing: The current line spacing, suitable for Chinese, appears too wide and leaves excessive blank space when used with English. Reducing line spacing for English text could improve content density and readability.

2. In-Line Paragraph Handling for Long Words: Currently, if a word is too long to fit at the end of a line (e.g., "visualizations"), the template compensates by expanding spaces between words. In standard English formatting, such a word should start on the next line without increased spacing between words on the previous line. I suggest adjusting this behavior to encourage users to rephrase sentences or reposition words when line breaks are necessary.

<img width="509" alt="image" src="https://github.com/user-attachments/assets/1212a9d8-6aba-46c5-83d3-0fc6429758fb">

If these adjustments align with the intended design approach, I can submit a PR to address these optimizations.

Thank you for your time!

**Comment by syhxzzz** [comment]
After making the second changee, I realized that as long as the left-aligned text near the end of the line doesn’t have significant gaps, it’s fine, and it doesn’t affect the overall appearance of the resume in Chinese.

However, for the first change, modifying the font’s line height and size too aggressively can impact the entire template’s appearance, so I made the adjustments carefully, especially with regard to line spacing.

In the original resume template, the line-height was set to 1.8. This felt slightly loose when using Chinese, but with English text, it might appear too spacious. Personally, I do perfer that a line-height of 1.5 better suits my aesthetic preferences. With this adjustment, both the Chinese and English parts of the resume look acceptable.

![img_v3_02gj_24f035bf-6bab-42bc-ba63-9bf53ad9538g](https://github.com/user-attachments/assets/b70f307f-f3d8-4479-bec9-07d1fd4b0af3)


Since there is a significant difference in style between Chinese and English, if the user is aiming for perfection, they may need to further customize the font size, line height, and other styles to better fit their needs.

**Comment by syhxzzz** [comment]
pr was raised in #24

**Comment by YiNNx** [comment]
Thank you for the detailed suggestions and observations!

I agree that optimizing line spacing and handling line breaks differently for English content could significantly improve readability and layout. Adjusting the line height seems like a balanced approach that works for both Chinese and English without overly compromising the template’s original design. I'll review PR #24 and provide feedback. Thanks again for your contribution!
