### ISSUE TITLE
可否利用 cssClass 来给特定md文件应用 css 样式？

### ISSUE THREAD

**Issue by zhaohongxuan** [BingyanStudio/LapisCV#4]
Obsidian 支持 cssClass，只要在 markdown 文件的 frontmatter 上加上 cssClasses信息，就不会将 css snippet 应用到整个 vault 的文件上了。也就不需要额外创建一个 vault 管理简历了。 
可以参考这里： https://forum.obsidian.md/t/css-for-specific-pages/13913

**Comment by YiNNx** [comment]
感谢建议！确实是更好的处理方式

**Comment by zhaohongxuan** [comment]
我尝试了一下在最外层套了个 `.resume` class，发现有一部分元素不起作用，对 css 不是很熟悉，没找到问题在哪里。

<img width="889" alt="image" src="https://github.com/BingyanStudio/LapisCV/assets/8613196/ba3e3872-458b-4edf-bcc9-cc531c1d9886">

<img width="1588" alt="image" src="https://github.com/BingyanStudio/LapisCV/assets/8613196/dd265aa0-fccc-4fe1-9a1e-76f5b2c52f1f">

**Comment by thewangcj** [comment]
> 我尝试了一下在最外层套了个 `.resume` class，发现有一部分元素不起作用，对 css 不是很熟悉，没找到问题在哪里。
> 
> <img alt="image" width="889" src="https://private-user-images.githubusercontent.com/8613196/313153082-ba3e3872-458b-4edf-bcc9-cc531c1d9886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDUzNDcsIm5iZiI6MTcxODYwNTA0NywicGF0aCI6Ii84NjEzMTk2LzMxMzE1MzA4Mi1iYTNlMzg3Mi00NThiLTRlZGYtYmNjOS1jYzUzMWMxZDk4ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDYxNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk1NGQxOTM1NGNlODg5Y2VjOWI0YmRmNWJiMDgzMmEzYjczY2FiYjU5MTk4NmVlMDNjYzJjOTc0MzgzYjc1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.46R2wSmxndGVEaWmMF60oqaUrg6qYouBjNnmRO24dL8"> <img alt="image" width="1588" src="https://private-user-images.githubusercontent.com/8613196/313152906-dd265aa0-fccc-4fe1-9a1e-76f5b2c52f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDUzNDcsIm5iZiI6MTcxODYwNTA0NywicGF0aCI6Ii84NjEzMTk2LzMxMzE1MjkwNi1kZDI2NWFhMC1mY2NjLTRmZTEtOWExZS03NmY1YjJjNTJmMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDYxNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIzYWFlODhjZGIwNGMyZjJlMWRjNGJjZWU4NzQxNWI3OWQ1YWE5MjcyY2EwMmFhODdkNGM4NTJjOWM1NTU1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QbMzC19oMahmShAxx3x_a-up7LOmoyK5CkdE8cfcd6k">

body 之外套一层类选择器是无效的，把 .resume 放到除了 body 之外的地方，也就是在 @media print { 这一行到最后的外面套上一层

**Comment by zhaohongxuan** [comment]
> > 我尝试了一下在最外层套了个 `.resume` class，发现有一部分元素不起作用，对 css 不是很熟悉，没找到问题在哪里。
> > <img alt="image" width="889" src="https://private-user-images.githubusercontent.com/8613196/313153082-ba3e3872-458b-4edf-bcc9-cc531c1d9886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDUzNDcsIm5iZiI6MTcxODYwNTA0NywicGF0aCI6Ii84NjEzMTk2LzMxMzE1MzA4Mi1iYTNlMzg3Mi00NThiLTRlZGYtYmNjOS1jYzUzMWMxZDk4ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDYxNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDk1NGQxOTM1NGNlODg5Y2VjOWI0YmRmNWJiMDgzMmEzYjczY2FiYjU5MTk4NmVlMDNjYzJjOTc0MzgzYjc1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.46R2wSmxndGVEaWmMF60oqaUrg6qYouBjNnmRO24dL8"> <img alt="image" width="1588" src="https://private-user-images.githubusercontent.com/8613196/313152906-dd265aa0-fccc-4fe1-9a1e-76f5b2c52f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDUzNDcsIm5iZiI6MTcxODYwNTA0NywicGF0aCI6Ii84NjEzMTk2LzMxMzE1MjkwNi1kZDI2NWFhMC1mY2NjLTRmZTEtOWExZS03NmY1YjJjNTJmMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDYxNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIzYWFlODhjZGIwNGMyZjJlMWRjNGJjZWU4NzQxNWI3OWQ1YWE5MjcyY2EwMmFhODdkNGM4NTJjOWM1NTU1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QbMzC19oMahmShAxx3x_a-up7LOmoyK5CkdE8cfcd6k">
> 
> body 之外套一层类选择器是无效的，把 .resume 放到除了 body 之外的地方，也就是在 @media print { 这一行到最后的外面套上一层

试了一下，确实可以了👍

**Comment by YiNNx** [comment]
使用 cssClass 来应用样式时，渲染和导出的效果会受已有的主题样式和 snippets 的影响，且使用 cssClass 导出的效果与原来有出入(#11)，因此暂时不考虑支持 cssClass，还是推荐使用独立 vault
