### ISSUE TITLE
第二页及之后的样式错误

### ISSUE THREAD

**Issue by jiz4oh** [BingyanStudio/LapisCV#5]
目前是只支持单页的样式吗？多页的时候 obsidian 样式显示不正确

**Comment by YiNNx** [comment]
具体是怎样不正确呢，Typora 的分页样式写得比较完善，Obsidian 确实可能有点页边距不适配问题

**Comment by jiz4oh** [comment]
<img width="940" alt="image" src="https://github.com/BingyanStudio/LapisCV/assets/41264693/d6feefdb-ff6f-4b6b-99bb-751a6c5a2f84">
只有第一页有背景页边距，第二页及之后都没有

**Comment by YiNNx** [comment]
已修复

**Comment by jiz4oh** [comment]
感谢 👍 已确认修复
