### ISSUE TITLE
Obsidian打开未按照预期显示

### ISSUE THREAD

**Issue by Liu8Can** [BingyanStudio/LapisCV#8]
![image](https://github.com/BingyanStudio/LapisCV/assets/102885173/494573c7-8573-4647-be57-17e0319fb230)
![image](https://github.com/BingyanStudio/LapisCV/assets/102885173/0ec58e4e-d183-4e38-8f84-70d88d6c36cf)

已按照要求，将 lapis-cv-obsidian 目录作为 Vault 在 Obsidian 打开

**Comment by YiNNx** [comment]
看起来打开路径不太对，多嵌套了一层 lapis-cv-obsidian 目录，可能是解压过程导致的，正常打开长这样

<img width="346" alt="Screenshot 2024-04-03 at 17 20 07" src="https://github.com/BingyanStudio/LapisCV/assets/86649490/4a795b9c-62b7-449c-9631-85983af59755">

**Comment by Liu8Can** [comment]
> 看起来打开路径不太对，多嵌套了一层 lapis-cv-obsidian 目录，可能是解压过程导致的，正常打开长这样
> 
> <img width="346" alt="Screenshot 2024-04-03 at 17 20 07" src="https://github.com/BingyanStudio/LapisCV/assets/86649490/4a795b9c-62b7-449c-9631-85983af59755">
> 
> 
> 

果然如此，解决了，谢谢
